<?php

namespace AppBundle\Repository;
use \Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuLikeRepository extends EntityRepository
{
    public function toutesLesNotes($menusolo)
    {
      $query = $this->createQueryBuilder('menulike')
        ->where('menulike.menuassociated = :menuassociated')
        ->setParameter('menuassociated', $menusolo)
        ->getQuery();

    return $query->getResult();
    }

    public function moyenneDesNotes($menusolo)
    {
      $query = $this->createQueryBuilder('menulike')
        ->select('AVG(menulike.rating)')
        ->where('menulike.menuassociated = :menuassociated')
        ->setParameter('menuassociated', $menusolo)
        ->getQuery();

    return $query->getSingleScalarResult();
    }


}
