<?php

namespace AppBundle\Repository;
use \Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{
    public function findMenuById($id)
    {
      $query = $this->createQueryBuilder('menu')
        ->where('menu.id = :id')
        ->setParameter('id', $id)
        ->getQuery();

    return $query->getSingleResult();
    }


    public function trierTousLesMenus()
    {
      $query = $this->createQueryBuilder('menu')
        ->orderBy('menu.name', 'DESC' )
        ->getQuery();

    return $query->getResult();
    }
}
